### ISSUE TITLE
docker網址無資料QQ

### ISSUE THREAD

**Issue by wibe01204** [ParrotXray/Mahiro-BOT#1]
![image](https://github.com/ParrotXray/Mahiro-BOT/assets/90883053/f87e50de-8fe4-47d0-8b8d-61a80a0155b6)

**Comment by ParrotXray** [comment]
> ![image](https://github.com/ParrotXray/Mahiro-BOT/assets/90883053/f87e50de-8fe4-47d0-8b8d-61a80a0155b6)
> 
> 

那個我已經刪掉了，太久沒看github了
